# Personal info
name: Iman Rofiq Syamsul
title: Curriculum Vitae
email: imanrofiqsy@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Mechatronics & Robotics
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Social links
# twitter_username: jekyllrb
instagram_username: imanrofiqsy
github_username:  imanrofiqsy

# Additional icon links

# About Section
about_profile_image: images/Iman.jpg

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
