title: Curriculum Vitae
email: imanrofiqsy@gmail.com

# The `>` after `description:` means to ignore line-breaks until next key.
# If you want to omit the line-break after the end of text, use `>-` instead.
description: >
  Mechatronic & Robotic

# Build settings

theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
    
instagram_username: imanrofiqsy
github_username:  imanrofiqsy

# If you want to link only specific pages in your header, uncomment this and add the path to the pages in
# order as they should show up.
#
# header_pages:
#   - about.md

# Set to `true` to show excerpts on the homepage.
#
# show_excerpts: false
